"""add property unit counts

Revision ID: 442c70a5adc5
Revises: 
Create Date: 2026-09-29 07:43:21.850704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '442c70a5adc5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "properties",
        sa.Column(
            "total_units",
            sa.Integer(),
            nullable=False,
            server_default="1"
        )
    )

    op.add_column(
        "properties",
        sa.Column(
            "available_units",
            sa.Integer(),
            nullable=False,
            server_default="1"
        )
    )

    # Remove the database-level defaults after existing rows
    # have been populated.
    op.alter_column(
        "properties",
        "total_units",
        server_default=None
    )

    op.alter_column(
        "properties",
        "available_units",
        server_default=None
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'available_units')
    op.drop_column('properties', 'total_units')
    # ### end Alembic commands ###
